import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'fr' | 'rw';

export interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, defaultText?: string) => string;
  translateCategory: (categoryName?: string) => string;
}

export const CATEGORY_TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    'Condoms': 'Condoms',
    'Condoms & Protection': 'Condoms & Protection',
    'Contraceptives': 'Contraceptives',
    'Pregnancy Tests': 'Pregnancy Tests',
    'Sex Time Enhancers': 'Sex Time Enhancers',
    'Lubricants': 'Lubricants',
    'Lubricants & Gels': 'Lubricants & Gels',
    'Vibrators & Massage': 'Vibrators & Massage',
    'Sensual & Lingerie': 'Sensual & Lingerie',
    'Hygiene & Wellness': 'Hygiene & Wellness',
    'Personal Care': 'Personal Care',
    'Sexual Wellness': 'Sexual Wellness',
    'Bestsellers': 'Bestsellers',
    'All': 'All Products',
    'All Products': 'All Products'
  },
  fr: {
    'Condoms': 'Préservatifs',
    'Condoms & Protection': 'Préservatifs & Protection',
    'Contraceptives': 'Contraceptifs',
    'Pregnancy Tests': 'Tests de Grossesse',
    'Sex Time Enhancers': 'Stimulants & Retardateurs',
    'Lubricants': 'Lubrifiants',
    'Lubricants & Gels': 'Lubrifiants & Gels',
    'Vibrators & Massage': 'Vibromasseurs & Massage',
    'Sensual & Lingerie': 'Lingerie & Sensuel',
    'Hygiene & Wellness': 'Hygiène & Bien-être',
    'Personal Care': 'Soins Personnels',
    'Sexual Wellness': 'Bien-être Sexuel',
    'Bestsellers': 'Meilleures Ventes',
    'All': 'Tous les Produits',
    'All Products': 'Tous les Produits'
  },
  rw: {
    'Condoms': 'Udukingirizo',
    'Condoms & Protection': 'Udukingirizo n\'Ibyo Gukingira',
    'Contraceptives': 'Ibinini n\'Uburyo bwo Kuboneza Urubyaro',
    'Pregnancy Tests': 'Ibipimo by\'Inda',
    'Sex Time Enhancers': 'Ibyongera Imbaraga n\'Igihe',
    'Lubricants': 'Amavuta yo Kworoshya',
    'Lubricants & Gels': 'Amavuta na Gel Byoroshya',
    'Vibrators & Massage': 'Ibyuma Byongera Ubushyuhe n\'Imyitozo',
    'Sensual & Lingerie': 'Imyenda n\'Ibikoresho by\'Urukundo',
    'Hygiene & Wellness': 'Isuku n\'Ubuzima Bwiza',
    'Personal Care': 'Kwita ku Mubiri',
    'Sexual Wellness': 'Ubuzima bw\'Imyororokere',
    'Bestsellers': 'Ibyakunzwe Cyane',
    'All': 'Ibicuruzwa Byose',
    'All Products': 'Ibicuruzwa Byose'
  }
};

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Top Bar
    'topbar.helpline': 'Helpline',
    'topbar.whatsapp': 'WhatsApp Live Chat',
    'topbar.discrete_banner': '100% Discrete Packaging & Privacy',
    'topbar.download_app': 'Download App',
    'topbar.app_installed': 'App Installed',
    'topbar.language': 'Language',
    'topbar.select_language': 'Select Language',

    // Navigation
    'nav.home': 'Home',
    'nav.shop': 'All Products',
    'nav.categories': 'Categories',
    'nav.track_order': 'Track Order',
    'nav.contact': 'Contact Us',
    'nav.faq': 'FAQ & Privacy',
    'nav.wishlist': 'Wishlist',
    'nav.cart': 'Cart',
    'nav.my_account': 'My Account',
    'nav.sign_in': 'Sign In',
    'nav.register': 'Register',
    'nav.logout': 'Sign Out',
    'nav.admin': 'Admin Dashboard',
    'nav.search_placeholder': 'Search condoms, intimacy, tests, wellness essentials...',
    'nav.browse_categories': 'Shop By Category',
    'nav.close': 'Close',
    'nav.menu': 'Menu',

    // Hero & Features
    'hero.badge': '100% Confidential Delivery in Rwanda',
    'hero.title': 'Discretion You Can Trust.',
    'hero.subtitle': 'Rwanda\'s most confidential store for intimate health, protection, testing kits, and personal wellness.',
    'hero.cta_shop': 'Shop Confidential Now',
    'hero.cta_track': 'Track Live Order',
    'hero.packaging_feature': 'Unbranded plain package box with discrete labeling',
    'hero.payment_feature': 'Instant MTN MoMo & Airtel Money pay',
    'hero.speed_feature': 'Express 30-90 min delivery in Kigali',

    // Common Actions
    'action.add_to_cart': 'Add to Cart',
    'action.buy_now': 'Buy Discreetly Now',
    'action.checkout': 'Proceed to Secure Checkout',
    'action.view_details': 'View Product',
    'action.filter': 'Filter',
    'action.search': 'Search',
    'action.clear_all': 'Clear All',
    'action.apply': 'Apply',
    'action.save': 'Save',
    'action.cancel': 'Cancel',
    'action.back': 'Back',
    'action.continue_shopping': 'Continue Shopping',
    'action.download': 'Download & Install',

    // Cart & Checkout
    'cart.title': 'Your Confidential Cart',
    'cart.empty': 'Your cart is currently empty',
    'cart.subtotal': 'Subtotal',
    'cart.delivery': 'Discrete Delivery',
    'cart.total': 'Total',
    'cart.free_delivery_notice': 'Plain unbranded package included',

    // Tracking
    'tracking.title': 'Track Your Discrete Order',
    'tracking.subtitle': 'Enter your Order ID and Phone Number to see real-time courier dispatch progress.',
    'tracking.order_id': 'Order ID',
    'tracking.phone': 'Phone Number',
    'tracking.track_button': 'Track Package Now',

    // Home Sections
    'home.shop_now': 'Shop Now',
    'home.track_order': 'Track Order',
    'home.browse_catalog': 'Browse Catalog',
    'home.hero_default_badge': '100% Discrete & Confidential',
    'home.hero_default_title': 'Quality Health & Intimate Wellness Care',
    'home.hero_default_desc': 'Safe, physician-approved products delivered in plain, unbranded packaging with complete privacy.',
    'home.categories_title': 'Shop By Category',
    'home.bestsellers_title': 'Bestsellers',
    'home.more_bestsellers': 'More Bestsellers',
    'home.on_discount_title': 'On Discount',
    'home.why_choose_us': 'Why Customers Trust CareMart',
    'home.why_choose_subtitle': 'Uncompromising privacy standards and certified body-safe products in Rwanda.',
    'home.plain_shipping_title': '100% Plain Shipping',
    'home.plain_shipping_desc': 'No store names or images on exterior box. Total confidentiality.',
    'home.statement_billing_title': 'Discreet Statement Billing',
    'home.statement_billing_desc': 'Charges on your account show only as generic "SS Global Retail".',
    'home.body_safe_title': 'Body-Safe Materials',
    'home.body_safe_desc': '100% medical grade silicone, phthalate-free certified formulations.',
    'home.fast_dispatch_title': 'Fast 24-Hour Dispatch',
    'home.fast_dispatch_desc': 'Orders placed before 2 PM are dispatched same business day in Kigali.',
    'home.cat_condoms': 'Condoms',
    'home.cat_contraceptives': 'Contraceptives',
    'home.cat_pregnancy_tests': 'Pregnancy Tests',
    'home.cat_time_enhancers': 'Sex Time Enhancers',
    'home.cat_lubricants': 'Lubricants',
    'home.cat_bestsellers': 'Bestsellers',

    // Partner Pharmacies & Marketplace
    'pharmacy.marketplace_title': 'Certified Pharmacy & Health Marketplace',
    'pharmacy.marketplace_desc': 'Regulated pharmaceutical products (such as contraceptive pills, family planning supplies, and pregnancy tests) are strictly fulfilled by our accredited, Ministry of Health-certified partner pharmacies in Rwanda. General intimate wellness items, water-based lubricants, skincare, and menstrual hygiene care are available directly.',
    'pharmacy.verified_partners': 'Verified Pharmacy Partners for Regulated Items',
    'pharmacy.general_wellness': 'General Wellness & Intimate Care Items',
    'pharmacy.confidential_packaging': '100% Confidential Parcel Packaging',
    'pharmacy.trust_title': 'Compliant & Confidential Fulfillment',
    'pharmacy.trust_desc': 'When ordering regulated pharmaceuticals, CareMart connects your order to a certified partner pharmacy for authorized fulfillment. All orders are delivered in plain, unbranded discrete packaging.',
    'pharmacy.slider_title': 'Our Certified Partner Pharmacies in Rwanda',
    'pharmacy.slider_subtitle': 'Accredited health partners fulfilling pharmaceutical & family planning orders',
    'pharmacy.certified_active': 'Certified Active',
    'pharmacy.moh_certified': 'Ministry of Health Certified',

    // Header and Dropdowns
    'header.user_greeting': 'Valued Member',
    'header.track_order_code': 'Track My Order Code',
    'header.account_orders': 'My Account & Orders',
    'header.download_app': 'Download Mobile App',
    'header.sign_out': 'Sign Out',
    'header.signin_or_track': 'Sign in or track discrete order code',
    'header.order_tracking_portal': 'Order Tracking Portal',
    'header.login': 'Log In',
    'header.create_account': 'Create Free Account',
    'header.download_app_full': 'Download Desktop/Mobile App',
    'header.menu': 'Menu',
    'header.app_button': 'App',

    // Cart Drawer
    'cart.discrete_cart': 'Your Discrete Cart',
    'cart.unique_items': 'unique items',
    'cart.empty_title': 'Your cart is currently empty',
    'cart.empty_desc': 'Explore our private collection of intimate wellness and body-safe personal products.',
    'cart.start_shopping': 'Start Shopping',
    'cart.each': 'each',
    'cart.promo_placeholder': 'Promo code (e.g. DISCRETION10)',
    'cart.coupon_label': 'Coupon',
    'cart.off': 'off',
    'cart.apply': 'Apply',
    'cart.remove': 'Remove',
    'cart.subtotal_label': 'Subtotal',
    'cart.discount_label': 'Discount',
    'cart.total_label': 'Total',
    'cart.discretion_billing_box': 'Shipped in unbranded plain box. Card billed as "SS Global".',
    'cart.proceed_checkout': 'Proceed to Secure Checkout',

    // Wishlist Page
    'wishlist.confidential_tag': 'Confidential Saved Items',
    'wishlist.title': 'Your Private Wishlist',
    'wishlist.saved_count': 'Saved',
    'wishlist.empty_title': 'Your Wishlist is Empty',
    'wishlist.empty_desc': 'Save items here for discrete viewing later or for quick future orders.',
    'wishlist.explore_catalog': 'Explore Catalog',

    // Product Card & Badges
    'badge.offer': 'OFFER',
    'badge.best_seller': 'BEST SELLER',
    'badge.secure_toys': 'SECURE TOYS',

    // Product Detail Page
    'product.save_amount': 'Save',
    'product.quantity': 'Quantity:',
    'product.in_stock': 'In Stock',
    'product.available': 'available',
    'product.add_to_cart': 'Add to Shopping Cart',
    'product.buy_now_1click': 'Buy Now with 1-Click',
    'product.add_to_wishlist': 'Add to Wishlist',
    'product.in_wishlist': 'In Your Private Wishlist',
    'product.suggested_title': 'Suggested Products',
    'product.more_items_in': 'More items in',
    'product.view_all_products': 'View All Products',

    // Checkout Page
    'checkout.title': 'Secure Checkout',
    'checkout.shipping_address_title': '1. Discrete Shipping Address',
    'checkout.full_name': 'Full Name *',
    'checkout.phone_number': 'Phone Number (For Courier SMS) *',
    'checkout.street_address': 'Street Address *',
    'checkout.apartment_landmark': 'Apartment / Landmark',
    'checkout.city_district': 'City / District *',
    'checkout.country': 'Country',
    'checkout.delivery_instructions': 'Delivery Instructions (Confidential)',
    'checkout.delivery_instructions_ph': 'e.g., Leave package at reception in plain packaging, call on arrival.',
    'checkout.payment_method_title': '2. Payment Method (Automated Verification)',
    'checkout.momo_title': 'MTN Mobile Money (MoMo)',
    'checkout.momo_desc': 'Instant prompt on phone (078/079)',
    'checkout.airtel_title': 'Airtel Money (Rwanda)',
    'checkout.airtel_desc': 'Instant prompt on phone (072/073)',
    'checkout.momo_phone_section_momo': 'MTN Mobile Money Phone Number',
    'checkout.momo_phone_section_airtel': 'Airtel Money Phone Number',
    'checkout.enter_momo_number': 'Enter Mobile Money Number (e.g., 0788123456 or 0731234567) *',
    'checkout.prompt_instruction': 'When you click Pay & Place Order, the system will send a push payment prompt to your phone and track confirmation automatically through the network.',
    'checkout.order_items': 'Order Items',
    'checkout.qty': 'Qty:',
    'checkout.items_subtotal': 'Items Subtotal',
    'checkout.grand_total': 'Grand Total',
    'checkout.discretion_assured': '100% Discretion Assured',
    'checkout.discretion_desc': 'Your order will be packaged in a plain, unbranded outer box without store branding.',
    'checkout.pay_and_place': 'Pay & Place Order',
    'checkout.processing_payment': 'Processing Payment...',

    // Shop Page & Filters & Product Grid
    'shop.title': 'All Discrete Products',
    'shop.desc': 'Browse body-safe health, wellness, and intimate accessories.',
    'shop.filters_button': 'Filters',
    'shop.active_filters': 'Active filters:',
    'shop.showing_items': 'discrete items',
    'shop.showing': 'Showing',
    'shop.sort_by': 'Sort by:',
    'shop.sort_featured': 'Featured & Recommended',
    'shop.sort_price_asc': 'Price: Low to High',
    'shop.sort_price_desc': 'Price: High to Low',
    'shop.sort_rating': 'Highest Customer Rating',
    'shop.sort_newest': 'Newest Arrivals',
    'shop.reset_all': 'Reset All',
    'shop.category_label': 'Category',
    'shop.all_products': 'All Products',
    'shop.max_price': 'Max Price:',
    'shop.brand_label': 'Brand',
    'shop.all_brands': 'All Brands',
    'shop.min_rating': 'Minimum Rating',
    'shop.and_above': '& above',
    'shop.in_stock_only': 'In Stock Only',
    'shop.clear_all': 'Clear all',
    'shop.filter_options': 'Filter Options',
    'shop.no_products_title': 'No Products Match Your Criteria',
    'shop.no_products_desc': 'Try broadening your price limit, changing selected category, or clearing search query filters.',

    // Footer
    'footer.discrete_store_desc': 'CareMart is Rwanda\'s #1 confidential health and personal wellness online store. Complete discretion guaranteed.',
    'footer.quick_links': 'Quick Links',
    'footer.customer_service': 'Customer Care',
    'footer.confidential_packaging': 'Confidential Delivery',
    'footer.rights': 'All rights reserved.',
    'footer.privacy_policy': 'Privacy & Discretion Policy',
    'footer.terms': 'Terms & Conditions',

    // Contact
    'contact.title': 'Confidential Support & Inquiries',
    'contact.subtitle': 'Our discreet support team is ready to assist you 24/7.',
    'contact.call_us': 'Call Helpline',
    'contact.whatsapp_us': 'WhatsApp Chat',
    'contact.location': 'Kigali, Rwanda',

    // FAQ Page
    'faq.tag': 'Help & Transparency',
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Everything you need to know about our privacy protocols, packaging, and body-safe materials.',
    'faq.q1': 'How will my package look when it arrives at my doorstep?',
    'faq.a1': 'All orders are shipped in standard, plain brown cardboard boxes or durable bubble mailers. There are zero store logos, product descriptions, or intimate graphics anywhere on the outer box or shipping label.',
    'faq.q2': 'What name will appear on my credit card / bank statement?',
    'faq.a2': 'To guarantee absolute financial privacy, all credit card and bank transactions are billed silently under the neutral descriptor "CM Retail" or "CM Online".',
    'faq.q3': 'Are your products certified 100% body-safe and non-toxic?',
    'faq.a3': 'Yes. Every item in our wellness catalog is crafted exclusively from medical-grade silicone, phthalate-free polymers, or hypoallergenic organic aloe formulations tested under strict quality standards.',
    'faq.q4': 'How fast is discrete order dispatch?',
    'faq.a4': 'Orders placed before 2:00 PM EST Monday through Friday are packaged and handed to the postal courier on the very same day. Standard discrete delivery takes 30-90 minutes in Kigali.',
    'faq.q5': 'What is your return policy for unopened items?',
    'faq.a5': 'Due to personal health and hygiene safety regulations, opened intimate items cannot be returned. However, any unopened, factory-sealed item can be returned within 30 days for a full refund using our plain return label.',
    'faq.q6': 'Can I track my shipment without disclosing contents?',
    'faq.a6': 'Yes. You will receive a confidential tracking link via email or in your account dashboard. Tracking updates show standard postal checkpoints without item details.',

    // Contact Page
    'contact.support_title': 'Confidential Customer Support',
    'contact.support_desc': 'Have questions regarding discrete packaging, shipping timelines, or product specifications? Our dedicated support team is available 24/7.',
    'contact.channels_title': 'Direct Contact Channels',
    'contact.email_support': 'Encrypted Email Support',
    'contact.response_time': 'Response within 2 hours',
    'contact.phone_whatsapp': 'Phone Call & WhatsApp',
    'contact.whatsapp_chat': 'WhatsApp Chat',
    'contact.call_now': 'Call Now',
    'contact.availability_247': 'Mon-Sun: 24/7 Availability',
    'contact.office_title': 'Discretion Office',
    'contact.office_location': 'Kigali Confidential Logistics Hub',
    'contact.office_promise': 'Plain Unbranded Packaging Assured',
    'contact.form_title': 'Send a Confidential Inquiry',
    'contact.your_name': 'Your Name *',
    'contact.name_placeholder': 'e.g. Marie Mutoni',
    'contact.your_email': 'Your Email Address *',
    'contact.email_placeholder': 'you@domain.com',
    'contact.your_phone': 'Phone Number (Optional)',
    'contact.subject_label': 'Subject',
    'contact.sub_order_shipping': 'Order & Discrete Shipping',
    'contact.sub_product_guidance': 'Product Material Guidance',
    'contact.sub_pharmacy_inquiry': 'Partner Pharmacy Inquiry',
    'contact.sub_billing_privacy': 'Billing & Privacy Inquiry',
    'contact.sub_return_request': 'Return or Exchange Request',
    'contact.your_message': 'Your Message *',
    'contact.placeholder_msg': 'How can we assist your private order...',
    'contact.send_btn': 'Send Confidential Inquiry',

    // Terms Page
    'terms.title': 'Terms & Conditions of Sale',
    'terms.effective_date': 'Effective Date: July 2026',
    'terms.age_title': '1. AGE REQUIREMENT',
    'terms.age_desc': 'You must be at least 18 years of age (or the legal age of majority in your jurisdiction) to purchase items from CareMart. By placing an order, you represent that you meet this age requirement.',
    'terms.safety_title': '2. PRODUCT INTENDED USE & SAFETY',
    'terms.safety_desc': 'All intimate care and wellness items offered on CareMart are designed for adult personal care and health planning. Users are advised to review product instructions, material compositions, and lubricant compatibility before use.',
    'terms.pricing_title': '3. PRICING & AVAILABILITY',
    'terms.pricing_desc': 'Prices listed on the website are in Rwandan Francs (Frw). We reserve the right to adjust pricing, promotional discounts, or stock counts at any time prior to order confirmation.',
    'terms.return_title': '4. HEALTH HYGIENE & RETURN POLICY',
    'terms.return_desc': 'Due to strict health and hygiene safety standards, opened or used intimate wellness products cannot be returned. Unopened, factory-sealed products may be returned within 30 days of delivery.',

    // Privacy Policy Page
    'privacy.title': 'Privacy Policy & Discretion Standards',
    'privacy.last_updated': 'Last updated: July 2026',
    'privacy.guarantee_title': 'Our Zero Data Sharing Guarantee',
    'privacy.guarantee_desc': 'At CareMart, your privacy is our single highest priority. We do not sell, rent, trade, or share your personal health data, purchase history, or email address with any third-party marketing companies under any circumstances.',
    'privacy.encryption_title': '1. DATA ENCRYPTION & SECURITY',
    'privacy.encryption_desc': 'All communications between your browser and our servers are encrypted using standard 256-bit SSL (Secure Sockets Layer) encryption protocol. Your credentials and order metadata are protected with industry-leading security rules.',
    'privacy.shipping_title': '2. DISCRETE SHIPPING PACKAGING',
    'privacy.shipping_desc': 'Products are packaged strictly in unbranded, plain cardboard boxes or bubble mailers. The exterior shipping label contains only recipient details and a neutral return address. No product details are visible.',
    'privacy.statement_title': '3. BANK STATEMENT ANONYMITY',
    'privacy.statement_desc': 'Your bank or Mobile Money statements will display only a neutral payment descriptor ("CM Retail" or "CM Online"). The name "CareMart" or individual item descriptions will never appear on your bank statements.',
    'privacy.cookies_title': '4. COOKIE POLICY',
    'privacy.cookies_desc': 'We use functional cookies strictly to maintain your active shopping cart items, preserve your wishlist preferences, and manage authentication state.',

    // Order Tracking Page
    'tracking.official_badge': 'Official Order Tracking Place',
    'tracking.page_title': 'Track Your Order',
    'tracking.page_desc': 'Enter the Order ID and the Phone Number used when placing your order to inspect live courier dispatch status and admin delivery updates.',
    'tracking.tab_id_phone': 'Track with Order ID & Phone',
    'tracking.tab_phone_only': 'Forgot Order ID? Track by Phone',
    'tracking.heading_id_phone': 'Enter Order ID & Phone Number',
    'tracking.heading_phone_only': 'Recover Your Order ID Using Your Phone Number',
    'tracking.label_order_id': 'Order ID / Tracking Code *',
    'tracking.label_phone': 'Phone Number Used *',
    'tracking.phone_help': 'Enter the MoMo, Airtel, or contact phone number you entered at checkout to find your Order ID.',
    'tracking.btn_find_and_track': 'Find My Order ID & Track Order',
    'tracking.btn_track_now': 'Track Order Now',
    'tracking.found_multiple': 'We found {count} orders associated with this phone number:',
    'tracking.recent_account_orders': 'Quick Tap From Your Account Orders:',
    'tracking.paid_success': 'Paid Successfully',
    'tracking.placed_on': 'Order Placed:',
    'tracking.copy_btn': 'Copy',
    'tracking.copied_btn': 'Copied',
    'tracking.timeline_title': 'Live Dispatch Status & Express Bike Journey',
    'tracking.step_paid': 'Order Paid & Confirmed',
    'tracking.step_paid_sub': 'Payment verified',
    'tracking.step_sealed': 'Closed Package Sealed',
    'tracking.step_sealed_sub': 'Unbranded box',
    'tracking.step_driver': 'Express Bike Driver',
    'tracking.step_driver_sub': 'Driver en route',
    'tracking.step_delivered': 'Delivered',
    'tracking.step_delivered_sub': 'Est. Same-Day Delivery',
    'tracking.courier_update_title': 'Admin & Express Courier Dispatch Update',
    'tracking.courier_note_prefix': 'Your order is currently',
    'tracking.courier_note_suffix': 'The driver will contact phone number upon arrival at your shipping destination.',
    'tracking.parcel_contents': 'Parcel Contents',
    'tracking.items_count': 'items',
    'tracking.qty': 'Qty:',
    'tracking.grand_total_paid': 'Grand Total Paid',
    'tracking.customer_shipping_info': 'Customer & Shipping Info',
    'tracking.customer_name': 'Customer Name',
    'tracking.destination': 'Delivery Destination',
    'tracking.instructions': 'Delivery Instructions',
    'tracking.confidential_promise': '100% Confidential Delivery',
    'tracking.confidential_box_desc': 'Plain unbranded box delivered fast.',
    'tracking.not_found_title': 'Order Credentials Not Matched',
    'tracking.not_found_desc': 'We couldn\'t find an order matching the entered Order ID and phone number. Please double check or contact customer care.',

    // Categories Page
    'catpage.badge': 'Complete Catalog Categories',
    'catpage.title': 'Explore By Health Category',
    'catpage.subtitle': 'From physician-approved protection and reproductive planning to premium luxury intimate care. Shipped with 100% discrete unbranded packaging.',
    'catpage.products_count': 'Products',
    'catpage.browse_cat': 'Browse'
  },
  fr: {
    // Top Bar
    'topbar.helpline': 'Assistance',
    'topbar.whatsapp': 'Chat WhatsApp en direct',
    'topbar.discrete_banner': 'Emballage 100% discret & confidentialité',
    'topbar.download_app': 'Télécharger l\'application',
    'topbar.app_installed': 'App installée',
    'topbar.language': 'Langue',
    'topbar.select_language': 'Choisir la langue',

    // Navigation
    'nav.home': 'Accueil',
    'nav.shop': 'Tous les Produits',
    'nav.categories': 'Catégories',
    'nav.track_order': 'Suivre Commande',
    'nav.contact': 'Contactez-nous',
    'nav.faq': 'FAQ & Confidentialité',
    'nav.wishlist': 'Favoris',
    'nav.cart': 'Panier',
    'nav.my_account': 'Mon Compte',
    'nav.sign_in': 'Connexion',
    'nav.register': 'S\'inscrire',
    'nav.logout': 'Déconnexion',
    'nav.admin': 'Tableau de bord Admin',
    'nav.search_placeholder': 'Rechercher préservatifs, intimité, tests, bien-être...',
    'nav.browse_categories': 'Acheter par catégorie',
    'nav.close': 'Fermer',
    'nav.menu': 'Menu',

    // Hero & Features
    'hero.badge': 'Livraison 100% confidentielle au Rwanda',
    'hero.title': 'Une discrétion en toute confiance.',
    'hero.subtitle': 'La boutique la plus confidentielle du Rwanda pour la santé intime, la protection, les tests et le bien-être.',
    'hero.cta_shop': 'Acheter en toute discrétion',
    'hero.cta_track': 'Suivi en direct',
    'hero.packaging_feature': 'Colis sans logo ni mention de produit',
    'hero.payment_feature': 'Paiement instantané MTN MoMo & Airtel Money',
    'hero.speed_feature': 'Livraison express 30-90 min à Kigali',

    // Common Actions
    'action.add_to_cart': 'Ajouter au Panier',
    'action.buy_now': 'Acheter Discrètement',
    'action.checkout': 'Passer à la Caisse Sécurisée',
    'action.view_details': 'Voir le Produit',
    'action.filter': 'Filtrer',
    'action.search': 'Rechercher',
    'action.clear_all': 'Tout Effacer',
    'action.apply': 'Appliquer',
    'action.save': 'Enregistrer',
    'action.cancel': 'Annuler',
    'action.back': 'Retour',
    'action.continue_shopping': 'Continuer mes Achats',
    'action.download': 'Télécharger & Installer',

    // Cart & Checkout
    'cart.title': 'Votre Panier Confidentiel',
    'cart.empty': 'Votre panier est actuellement vide',
    'cart.subtotal': 'Sous-total',
    'cart.delivery': 'Livraison Discrète',
    'cart.total': 'Total',
    'cart.free_delivery_notice': 'Emballage discret neutre inclus',

    // Tracking
    'tracking.title': 'Suivre votre Commande Discrète',
    'tracking.subtitle': 'Entrez votre ID de commande et votre numéro de téléphone pour voir l\'état du livreur en temps réel.',
    'tracking.order_id': 'ID de Commande',
    'tracking.phone': 'Numéro de Téléphone',
    'tracking.track_button': 'Suivre le Colis',

    // Home Sections
    'home.shop_now': 'Acheter Maintenant',
    'home.track_order': 'Suivre Commande',
    'home.browse_catalog': 'Parcourir le Catalogue',
    'home.hero_default_badge': '100% DISCRET & CONFIDENTIEL',
    'home.hero_default_title': 'Santé & Bien-être Intime Certifiés',
    'home.hero_default_desc': 'Produits sûrs, approuvés par des professionnels et livrés dans un emballage neutre et confidentiel.',
    'home.categories_title': 'Acheter par Catégorie',
    'home.bestsellers_title': 'Meilleures Ventes',
    'home.more_bestsellers': 'Plus de Meilleures Ventes',
    'home.on_discount_title': 'En Promotion',
    'home.why_choose_us': 'Pourquoi les Clients Font Confiance à CareMart',
    'home.why_choose_subtitle': 'Normes de confidentialité strictes et produits certifiés conformes au Rwanda.',
    'home.plain_shipping_title': '100% Emballage Neutre',
    'home.plain_shipping_desc': 'Aucun logo ni nom de boutique sur le carton extérieur. Discrétion totale.',
    'home.statement_billing_title': 'Relevé de Paiement Discret',
    'home.statement_billing_desc': 'Les transactions apparaissent sous un libellé générique neutre.',
    'home.body_safe_title': 'Matériaux Certifiés Sûrs',
    'home.body_safe_desc': 'Silicone 100% médical de haute qualité, sans phtalates.',
    'home.fast_dispatch_title': 'Expédition Rapide 24H',
    'home.fast_dispatch_desc': 'Les commandes passées avant 14h sont expédiées le jour même à Kigali.',
    'home.cat_condoms': 'Préservatifs',
    'home.cat_contraceptives': 'Contraceptifs',
    'home.cat_pregnancy_tests': 'Tests de Grossesse',
    'home.cat_time_enhancers': 'Retardateurs & Énergie',
    'home.cat_lubricants': 'Lubrifiants',
    'home.cat_bestsellers': 'Meilleures Ventes',

    // Partner Pharmacies & Marketplace
    'pharmacy.marketplace_title': 'Pharmacie Agréée & Espace Santé',
    'pharmacy.marketplace_desc': 'Les produits pharmaceutiques réglementés (tels que les pilules contraceptives, le matériel de planning familial et les tests de grossesse) sont rigoureusement délivrés par nos pharmacies partenaires agréées par le Ministère de la Santé au Rwanda. Les articles de bien-être intime, lubrifiants et soins d\'hygiène sont disponibles directement.',
    'pharmacy.verified_partners': 'Pharmacies Partenaires Vérifiées pour Produits Réglementés',
    'pharmacy.general_wellness': 'Bien-être Général & Soins Intimes',
    'pharmacy.confidential_packaging': '100% Emballage Colis Confidentiel',
    'pharmacy.trust_title': 'Délivrance Conforme & Confidentielle',
    'pharmacy.trust_desc': 'Lors de la commande de produits pharmaceutiques réglementés, CareMart transmet votre commande à une pharmacie partenaire certifiée pour une préparation autorisée. Tous les colis sont livrés sous emballage neutre et discret.',
    'pharmacy.slider_title': 'Nos Pharmacies Partenaires Agréées au Rwanda',
    'pharmacy.slider_subtitle': 'Partenaires de santé agréés assurant la délivrance pharmaceutique et du planning familial',
    'pharmacy.certified_active': 'Certifié Actif',
    'pharmacy.moh_certified': 'Certifié Ministère de la Santé',

    // Header and Dropdowns
    'header.user_greeting': 'Membre Estimé',
    'header.track_order_code': 'Suivre Mon Code de Commande',
    'header.account_orders': 'Mon Compte & Commandes',
    'header.download_app': 'Télécharger l\'Application Mobile',
    'header.sign_out': 'Se Déconnecter',
    'header.signin_or_track': 'Connectez-vous ou suivez un code de commande',
    'header.order_tracking_portal': 'Portail de Suivi des Commandes',
    'header.login': 'Connexion',
    'header.create_account': 'Créer un Compte Gratuit',
    'header.download_app_full': 'Télécharger l\'Application PC/Mobile',
    'header.menu': 'Menu',
    'header.app_button': 'App',

    // Cart Drawer
    'cart.discrete_cart': 'Votre Panier Discret',
    'cart.unique_items': 'articles uniques',
    'cart.empty_title': 'Votre panier est actuellement vide',
    'cart.empty_desc': 'Découvrez notre collection privée de bien-être intime et de produits sûrs pour le corps.',
    'cart.start_shopping': 'Commencer vos Achats',
    'cart.each': 'l\'unité',
    'cart.promo_placeholder': 'Code promo (ex: DISCRETION10)',
    'cart.coupon_label': 'Coupon',
    'cart.off': 'de réduction',
    'cart.apply': 'Appliquer',
    'cart.remove': 'Supprimer',
    'cart.subtotal_label': 'Sous-total',
    'cart.discount_label': 'Réduction',
    'cart.total_label': 'Total',
    'cart.discretion_billing_box': 'Expédié dans un carton neutre sans marque. Facturation discrète "SS Global".',
    'cart.proceed_checkout': 'Passer au Paiement Sécurisé',

    // Wishlist Page
    'wishlist.confidential_tag': 'Articles Enregistrés Confidentiels',
    'wishlist.title': 'Votre Liste d\'Envies Privée',
    'wishlist.saved_count': 'Enregistrés',
    'wishlist.empty_title': 'Votre Liste d\'Envies est Vide',
    'wishlist.empty_desc': 'Enregistrez des articles ici pour les consulter plus tard en toute discrétion ou commander rapidement.',
    'wishlist.explore_catalog': 'Explorer le Catalogue',

    // Product Card & Badges
    'badge.offer': 'OFFRE',
    'badge.best_seller': 'MEILLEURE VENTE',
    'badge.secure_toys': 'BIEN-ÊTRE INTIME',

    // Product Detail Page
    'product.save_amount': 'Économisez',
    'product.quantity': 'Quantité :',
    'product.in_stock': 'En stock',
    'product.available': 'disponibles',
    'product.add_to_cart': 'Ajouter au Panier',
    'product.buy_now_1click': 'Acheter en 1 Clic',
    'product.add_to_wishlist': 'Ajouter à la Liste d\'Envies',
    'product.in_wishlist': 'Dans votre Liste d\'Envies Privée',
    'product.suggested_title': 'Produits Recommandés',
    'product.more_items_in': 'Plus d\'articles dans',
    'product.view_all_products': 'Voir Tous les Produits',

    // Checkout Page
    'checkout.title': 'Paiement Sécurisé',
    'checkout.shipping_address_title': '1. Adresse de Livraison Discrète',
    'checkout.full_name': 'Nom Complet *',
    'checkout.phone_number': 'Numéro de Téléphone (Pour SMS du Coursier) *',
    'checkout.street_address': 'Adresse / Rue *',
    'checkout.apartment_landmark': 'Appartement / Point de Repère',
    'checkout.city_district': 'Ville / District *',
    'checkout.country': 'Pays',
    'checkout.delivery_instructions': 'Instructions de Livraison (Confidentielles)',
    'checkout.delivery_instructions_ph': 'ex : Laisser le colis à la réception sous emballage neutre, appeler à l\'arrivée.',
    'checkout.payment_method_title': '2. Mode de Paiement (Vérification Automatique)',
    'checkout.momo_title': 'MTN Mobile Money (MoMo)',
    'checkout.momo_desc': 'Notification instantanée sur le téléphone (078/079)',
    'checkout.airtel_title': 'Airtel Money (Rwanda)',
    'checkout.airtel_desc': 'Notification instantanée sur le téléphone (072/073)',
    'checkout.momo_phone_section_momo': 'Numéro de Téléphone MTN Mobile Money',
    'checkout.momo_phone_section_airtel': 'Numéro de Téléphone Airtel Money',
    'checkout.enter_momo_number': 'Entrez le numéro Mobile Money (ex : 0788123456 ou 0731234567) *',
    'checkout.prompt_instruction': 'Lorsque vous cliquez sur Payer et Commander, le système enverra une demande de paiement sur votre téléphone et confirmera automatiquement la transaction.',
    'checkout.order_items': 'Articles Commandés',
    'checkout.qty': 'Qté :',
    'checkout.items_subtotal': 'Sous-total des Articles',
    'checkout.grand_total': 'Total Général',
    'checkout.discretion_assured': '100% Discrétion Assurée',
    'checkout.discretion_desc': 'Votre commande sera emballée dans un carton neutre sans logo ni mention de la boutique.',
    'checkout.pay_and_place': 'Payer & Commander',
    'checkout.processing_payment': 'Traitement du Paiement...',

    // Shop Page & Filters & Product Grid
    'shop.title': 'Tous les Produits Confidentiels',
    'shop.desc': 'Parcourez nos accessoires de santé, bien-être et intimité certifiés sûrs.',
    'shop.filters_button': 'Filtres',
    'shop.active_filters': 'Filtres actifs :',
    'shop.showing_items': 'articles confidentiels',
    'shop.showing': 'Affichage de',
    'shop.sort_by': 'Trier par :',
    'shop.sort_featured': 'Recommandés & En Vedette',
    'shop.sort_price_asc': 'Prix : Croissant',
    'shop.sort_price_desc': 'Prix : Décroissant',
    'shop.sort_rating': 'Meilleurs Avis Clients',
    'shop.sort_newest': 'Nouveautés',
    'shop.reset_all': 'Tout Réinitialiser',
    'shop.category_label': 'Catégorie',
    'shop.all_products': 'Tous les Produits',
    'shop.max_price': 'Prix Max :',
    'shop.brand_label': 'Marque',
    'shop.all_brands': 'Toutes les Marques',
    'shop.min_rating': 'Note Minimale',
    'shop.and_above': '& au-dessus',
    'shop.in_stock_only': 'En Stock Uniquement',
    'shop.clear_all': 'Effacer tout',
    'shop.filter_options': 'Options de Filtrage',
    'shop.no_products_title': 'Aucun produit ne correspond à vos critères',
    'shop.no_products_desc': 'Essayez d\'élargir votre limite de prix, de modifier la catégorie ou d\'effacer la recherche.',

    // Footer
    'footer.discrete_store_desc': 'CareMart est la boutique en ligne n°1 au Rwanda pour la santé intime et le bien-être confidentiel.',
    'footer.quick_links': 'Liens Rapides',
    'footer.customer_service': 'Service Client',
    'footer.confidential_packaging': 'Livraison Confidentielle',
    'footer.rights': 'Tous droits réservés.',
    'footer.privacy_policy': 'Politique de Confidentialité',
    'footer.terms': 'Conditions Générales',

    // Contact
    'contact.title': 'Support Confidentiel & Questions',
    'contact.subtitle': 'Notre équipe d\'assistance discrète est prête à vous aider 24h/24 et 7j/7.',
    'contact.call_us': 'Appeler le Support',
    'contact.whatsapp_us': 'Chat WhatsApp',
    'contact.location': 'Kigali, Rwanda',

    // FAQ Page
    'faq.tag': 'Aide & Transparence',
    'faq.title': 'Foire Aux Questions',
    'faq.subtitle': 'Tout ce que vous devez savoir sur nos protocoles de confidentialité, nos emballages discrets et nos produits sûrs.',
    'faq.q1': 'À quoi ressemblera mon colis à son arrivée ?',
    'faq.a1': 'Toutes les commandes sont expédiées dans des boîtes en carton marron neutres ou des enveloppes à bulles durables. Aucun logo de boutique, description de produit ou image intime ne figure sur l\'emballage ou l\'étiquette d\'expédition.',
    'faq.q2': 'Quel nom apparaîtra sur mon relevé bancaire / Mobile Money ?',
    'faq.a2': 'Pour garantir une confidentialité financière totale, toutes les transactions sont discrètement libellées sous le nom neutre « CM Retail » ou « CM Online ».',
    'faq.q3': 'Vos produits sont-ils certifiés 100% sûrs pour le corps et non toxiques ?',
    'faq.a3': 'Oui. Chaque article de notre catalogue bien-être est fabriqué exclusivement en silicone de qualité médicale, polymères sans phtalates ou formules d\'aloe vera bio hypoallergéniques certifiées.',
    'faq.q4': 'Quel est le délai d\'expédition discrète ?',
    'faq.a4': 'Les commandes passées avant 14h00 du lundi au vendredi sont emballées et expédiées le jour même. La livraison discrète prend 30 à 90 minutes à Kigali.',
    'faq.q5': 'Quelle est votre politique de retour pour les articles non ouverts ?',
    'faq.a5': 'En raison de la réglementation sur l\'hygiène et la santé personnelle, les articles intimes ouverts ne peuvent être retournés. En revanche, tout article scellé et non ouvert peut être retourné sous 30 jours pour un remboursement complet.',
    'faq.q6': 'Puis-je suivre mon colis sans dévoiler son contenu ?',
    'faq.a6': 'Oui. Vous recevrez un lien de suivi confidentiel par SMS/e-mail ou dans votre espace compte. Le suivi affiche uniquement les étapes de transport postal sans aucun détail sur les articles.',

    // Contact Page
    'contact.support_title': 'Support Client Confidentiel',
    'contact.support_desc': 'Des questions sur l\'emballage discret, les délais de livraison ou les caractéristiques des produits ? Notre équipe dédiée est disponible 24h/24 et 7j/7.',
    'contact.channels_title': 'Canaux de Contact Direct',
    'contact.email_support': 'Assistance E-mail Sécurisée',
    'contact.response_time': 'Réponse sous 2 heures',
    'contact.phone_whatsapp': 'Appel Téléphonique & WhatsApp',
    'contact.whatsapp_chat': 'Chat WhatsApp',
    'contact.call_now': 'Appeler Maintenant',
    'contact.availability_247': 'Lun-Dim : Disponible 24h/24 et 7j/7',
    'contact.office_title': 'Centre Logistique Confidentiel',
    'contact.office_location': 'Centre Logistique Confidentiel de Kigali',
    'contact.office_promise': 'Emballage neutre sans logo garanti',
    'contact.form_title': 'Envoyer un Message Confidentiel',
    'contact.your_name': 'Votre Nom *',
    'contact.name_placeholder': 'ex. Marie Mutoni',
    'contact.your_email': 'Votre Adresse E-mail *',
    'contact.email_placeholder': 'vous@domaine.com',
    'contact.your_phone': 'Numéro de Téléphone (Facultatif)',
    'contact.subject_label': 'Sujet',
    'contact.sub_order_shipping': 'Commande & Livraison Discrète',
    'contact.sub_product_guidance': 'Conseils sur les Produits & Matériaux',
    'contact.sub_pharmacy_inquiry': 'Question sur les Pharmacies Partenaires',
    'contact.sub_billing_privacy': 'Facturation & Confidentialité',
    'contact.sub_return_request': 'Demande de Retour ou d\'Échange',
    'contact.your_message': 'Votre Message *',
    'contact.placeholder_msg': 'Comment pouvons-nous vous aider pour votre commande discrète...',
    'contact.send_btn': 'Envoyer le Message Confidentiel',

    // Terms Page
    'terms.title': 'Conditions Générales de Vente',
    'terms.effective_date': 'Date d\'effet : Juillet 2026',
    'terms.age_title': '1. CONDITION D\'ÂGE',
    'terms.age_desc': 'Vous devez avoir au moins 18 ans (ou l\'âge légal de la majorité dans votre pays) pour commander sur CareMart. En passant commande, vous déclarez respecter cette condition d\'âge.',
    'terms.safety_title': '2. UTILISATION PRÉVUE & SÉCURITÉ DES PRODUITS',
    'terms.safety_desc': 'Tous les articles de santé intime et de bien-être sur CareMart sont conçus pour les soins personnels et la planification familiale des adultes. Les clients sont invités à consulter les notices avant utilisation.',
    'terms.pricing_title': '3. PRIX & DISPONIBILITÉ',
    'terms.pricing_desc': 'Les prix affichés sur le site sont en Francs Rwandais (Frw). Nous nous réservons le droit d\'ajuster les tarifs, réductions ou niveaux de stock avant confirmation de la commande.',
    'terms.return_title': '4. HYGIÈNE & POLITIQUE DE RETOUR',
    'terms.return_desc': 'En raison de normes strictes d\'hygiène et de sécurité, les articles intimes ouverts ou utilisés ne peuvent être retournés. Les articles scellés dans leur emballage d\'origine peuvent être retournés dans un délai de 30 jours.',

    // Privacy Policy Page
    'privacy.title': 'Politique de Confidentialité & Normes de Discrétion',
    'privacy.last_updated': 'Dernière mise à jour : Juillet 2026',
    'privacy.guarantee_title': 'Notre Garantie Zéro Partage de Données',
    'privacy.guarantee_desc': 'Chez CareMart, votre confidentialité est notre priorité absolue. Nous ne vendons, ne louons, n\'échangeons et ne partageons en aucun cas vos données de santé, votre historique d\'achat ou votre e-mail avec des tiers publicitaires.',
    'privacy.encryption_title': '1. CHIFFREMENT & SÉCURITÉ DES DONNÉES',
    'privacy.encryption_desc': 'Toutes les communications entre votre navigateur et nos serveurs sont protégées par le protocole de chiffrement SSL 256 bits standard. Vos identifiants et métadonnées de commande bénéficient d\'une sécurité maximale.',
    'privacy.shipping_title': '2. EMBALLAGE D\'EXPÉDITION DISCRET',
    'privacy.shipping_desc': 'Les produits sont expédiés dans des cartons neutres ou des enveloppes à bulles sans marque. L\'étiquette extérieure ne comporte que les coordonnées du destinataire et une adresse neutre, sans mention du contenu.',
    'privacy.statement_title': '3. ANONYMAT DES RELEVÉS BANCAIRES / MOMO',
    'privacy.statement_desc': 'Vos relevés bancaires ou Mobile Money n\'affichent qu\'un libellé commercial neutre (« CM Retail » ou « CM Online »). Le nom « CareMart » ou le nom des articles n\'y figurera jamais.',
    'privacy.cookies_title': '4. POLITIQUE RELATIVE AUX COOKIES',
    'privacy.cookies_desc': 'Nous utilisons des cookies fonctionnels uniquement pour conserver vos articles dans le panier, sauvegarder vos favoris et sécuriser votre session de connexion.',

    // Order Tracking Page
    'tracking.official_badge': 'Espace Officiel de Suivi de Commande',
    'tracking.page_title': 'Suivre Votre Commande',
    'tracking.page_desc': 'Entrez le N° de Commande (Order ID) et le Numéro de Téléphone utilisés lors de l\'achat pour consulter l\'état d\'avancement de la livraison moto express en direct.',
    'tracking.tab_id_phone': 'Suivi avec N° de Commande & Tél',
    'tracking.tab_phone_only': 'N° de commande oublié ? Par Téléphone',
    'tracking.heading_id_phone': 'Entrez le N° de Commande & le Téléphone',
    'tracking.heading_phone_only': 'Retrouvez votre N° de Commande avec votre Téléphone',
    'tracking.label_order_id': 'N° de Commande / Code de Suivi *',
    'tracking.label_phone': 'Numéro de Téléphone Utilisé *',
    'tracking.phone_help': 'Entrez le numéro MoMo, Airtel ou de contact fourni lors de la commande pour retrouver votre N° de commande.',
    'tracking.btn_find_and_track': 'Trouver mon N° et Suivre',
    'tracking.btn_track_now': 'Suivre la Commande Maintenant',
    'tracking.found_multiple': 'Nous avons trouvé {count} commandes associées à ce numéro :',
    'tracking.recent_account_orders': 'Sélection rapide depuis votre compte :',
    'tracking.paid_success': 'Payé avec Succès',
    'tracking.placed_on': 'Date de Commande :',
    'tracking.copy_btn': 'Copier',
    'tracking.copied_btn': 'Copié',
    'tracking.timeline_title': 'Statut de Livraison en Direct & Trajet Moto Express',
    'tracking.step_paid': 'Commande Payée & Confirmée',
    'tracking.step_paid_sub': 'Paiement vérifié',
    'tracking.step_sealed': 'Colis Discret Scellé',
    'tracking.step_sealed_sub': 'Boîte neutre sans marque',
    'tracking.step_driver': 'Livreur Moto Express',
    'tracking.step_driver_sub': 'Livreur en route',
    'tracking.step_delivered': 'Livré',
    'tracking.step_delivered_sub': 'Livraison le jour même',
    'tracking.courier_update_title': 'Mise à jour Expédition & Livreur Express',
    'tracking.courier_note_prefix': 'Votre commande est actuellement',
    'tracking.courier_note_suffix': 'Le livreur contactera le numéro de téléphone à l\'arrivée à votre adresse de livraison.',
    'tracking.parcel_contents': 'Contenu du Colis',
    'tracking.items_count': 'articles',
    'tracking.qty': 'Qté :',
    'tracking.grand_total_paid': 'Montant Total Payé',
    'tracking.customer_shipping_info': 'Infos Client & Livraison',
    'tracking.customer_name': 'Nom du Client',
    'tracking.destination': 'Destination de Livraison',
    'tracking.instructions': 'Instructions de Livraison',
    'tracking.confidential_promise': 'Livraison 100% Confidentielle',
    'tracking.confidential_box_desc': 'Boîte neutre sans mention livrée rapidement.',
    'tracking.not_found_title': 'Coordonnées de Commande Non Trouvées',
    'tracking.not_found_desc': 'Nous n\'avons trouvé aucune commande correspondant au N° de commande et numéro saisis. Veuillez vérifier vos informations.',

    // Categories Page
    'catpage.badge': 'Catalogue Complet des Catégories',
    'catpage.title': 'Explorer par Catégorie de Santé',
    'catpage.subtitle': 'De la protection et planification familiale aux soins de bien-être intime haut de gamme. Expédié en colis 100% discret et sans marque.',
    'catpage.products_count': 'Produits',
    'catpage.browse_cat': 'Parcourir'
  },
  rw: {
    // Top Bar
    'topbar.helpline': 'Ubufasha kuri terefone',
    'topbar.whatsapp': 'Kuvugana kuri WhatsApp',
    'topbar.discrete_banner': 'Gupfunyika mu ibanga 100% & Umutekano',
    'topbar.download_app': 'Kumanura Porogaramu',
    'topbar.app_installed': 'Yinjijwe muri telefone',
    'topbar.language': 'Ururimi',
    'topbar.select_language': 'Hitamo Ururimi',

    // Navigation
    'nav.home': 'Ahabanza',
    'nav.shop': 'Ibicuruzwa Byose',
    'nav.categories': 'Ibyiciro',
    'nav.track_order': 'Kurikirana Icyo Waguze',
    'nav.contact': 'Twandikire',
    'nav.faq': 'Ibibazo Bikunze Kubazwa',
    'nav.wishlist': 'Ibyo Nkunda',
    'nav.cart': 'Icyibo',
    'nav.my_account': 'Konte Yanjye',
    'nav.sign_in': 'Injira',
    'nav.register': 'Iyandikishe',
    'nav.logout': 'Sohoka',
    'nav.admin': 'Ubuyobozi',
    'nav.search_placeholder': 'Shakisha udukingirizo, iby\'ubuzima bw\'imyororokere, ibipimo...',
    'nav.browse_categories': 'Gura ukurikije Ibyiciro',
    'nav.close': 'Funga',
    'nav.menu': 'Ibikubiyemo',

    // Hero & Features
    'hero.badge': 'Kugezwaho ibicuruzwa mu ibanga rikomeye mu Rwanda 100%',
    'hero.title': 'Ibanga Risesuye Wizeye.',
    'hero.subtitle': 'Iduka rya mbere mu Rwanda ryo kugura iby\'ubuzima bw\'imyororokere, gukingira, ibipimo byihuse n\'isuku yihariye mu ibanga.',
    'hero.cta_shop': 'Gura mu Ibanga None',
    'hero.cta_track': 'Kurikirana Icyo Waguze',
    'hero.packaging_feature': 'Ikarito ifunze neza itanditsweho ibirimo',
    'hero.payment_feature': 'Kwishyura ako kanya na MTN MoMo na Airtel Money',
    'hero.speed_feature': 'Kugezwaho ibyo waguze mu minota 30-90 i Kigali',

    // Common Actions
    'action.add_to_cart': 'Oshya mu Cyibo',
    'action.buy_now': 'Gura mu Ibanga Ako Kanya',
    'action.checkout': 'Komeza Kwishyura mu Mutekano',
    'action.view_details': 'Reba Iki Gicuruzwa',
    'action.filter': 'Gutoranya',
    'action.search': 'Shakisha',
    'action.clear_all': 'Guhanagura Byose',
    'action.apply': 'Koresha',
    'action.save': 'Bika',
    'action.cancel': 'Kureka',
    'action.back': 'Gusubira Inyuma',
    'action.continue_shopping': 'Komeza Gahaha',
    'action.download': 'Manura & Shyira muri Telefone',

    // Cart & Checkout
    'cart.title': 'Icyibo Cyawe Cy\'Ibanga',
    'cart.empty': 'Icyibo cyawe kiracyarimo ubusa',
    'cart.subtotal': 'Igiteranyo Cy\'ibicuruzwa',
    'cart.delivery': 'Kugezwaho mu Ibanga',
    'cart.total': 'Amafaranga Yose hamwe',
    'cart.free_delivery_notice': 'Gupfunyika mu ibanga nta kimenyetso kirimo',

    // Tracking
    'tracking.title': 'Kurikirana aho Icyo Waguze Kigeze',
    'tracking.subtitle': 'Shyiramo nimero y\'icyo waguze (Order ID) na terefone yawe urebe aho umumotari ageze.',
    'tracking.order_id': 'Nimero y\'ibyo Waguze',
    'tracking.phone': 'Nimero ya Terefone',
    'tracking.track_button': 'Kurikirana Ako Kanya',

    // Home Sections
    'home.shop_now': 'Gura Ubu',
    'home.track_order': 'Kurikirana Ibyo Waguze',
    'home.browse_catalog': 'Reba Ibyo Dufite Byose',
    'home.hero_default_badge': 'IBANGA N\'UMUTEKANO 100%',
    'home.hero_default_title': 'Ubuzima Bw\'Imyororokere n\'Isuku Yihariye',
    'home.hero_default_desc': 'Ibicuruzwa byujuje ubuziranenge byemewe n\'abaganga, bipfunyitse mu ibanga rikomeye.',
    'home.categories_title': 'Gura Ukurikije Ibyiciro',
    'home.bestsellers_title': 'Ibyakunzwe Cyane',
    'home.more_bestsellers': 'Reba Ibindi Byakunzwe',
    'home.on_discount_title': 'Ibigabanyirijwe Ibiciro',
    'home.why_choose_us': 'Impamvu Abakiriya Bizera CareMart',
    'home.why_choose_subtitle': 'Umutekano n\'ibanga rikomeye ku bicuruzwa byose byemewe n\'abaganga mu Rwanda.',
    'home.plain_shipping_title': 'Gupfunyika mu Ibanga 100%',
    'home.plain_shipping_desc': 'Ikarito ifunze neza itariho amazina cyangwa ifoto y\'ibigurishijwe. Ibanga 100%.',
    'home.statement_billing_title': 'Ubutumwa bw\'Ubwishyu Bwihishe',
    'home.statement_billing_desc': 'Kuri konti yawe cyangwa MoMo hagaragaraho izina rusange ridafitanye isano n\'ibyo waguze.',
    'home.body_safe_title': 'Ibikoresho Bizewe ku Buzima',
    'home.body_safe_desc': 'Byose bikozwe muri silicone yujuje ubuziranenge bwo mu rwego rw\'ubuvuzi.',
    'home.fast_dispatch_title': 'Kugezwaho Ibicuruzwa Byihuse',
    'home.fast_dispatch_desc': 'Ibyo utumije mbere ya saa munani z\'amanywa bikugeraho uwo munsi i Kigali.',
    'home.cat_condoms': 'Udukingirizo',
    'home.cat_contraceptives': 'Ibyo Kuboneza Urubyaro',
    'home.cat_pregnancy_tests': 'Ibipimo by\'Inda',
    'home.cat_time_enhancers': 'Ibyongera Imbaraga n\'Igihe',
    'home.cat_lubricants': 'Amavuta n\'Ibinyerera',
    'home.cat_bestsellers': 'Ibyakunzwe Cyane',

    // Partner Pharmacies & Marketplace
    'pharmacy.marketplace_title': 'Amafarumasi n\'Ububiko bw\'Ubuzima Byemewe',
    'pharmacy.marketplace_desc': 'Imiti igengwa n\'amategeko (nk\'ibinini byo kuboneza urubyaro, n\'ibipimo by\'inda) itangwa n\'amafarumasi yemewe na Minisiteri y\'Ubuzima dufatanyije mu Rwanda. Ibikoresho by\'isuku n\'amavuta byo bihabwa umukiriya ako kanya.',
    'pharmacy.verified_partners': 'Amafarumasi Yemejwe ku Bicuruzwa Byihariye',
    'pharmacy.general_wellness': 'Isuku Rusange n\'Ubuzima Bwite',
    'pharmacy.confidential_packaging': '100% Gupfunyika mu Ibanga Rikomeye',
    'pharmacy.trust_title': 'Gutanga Ibicuruzwa mu Burinzi n\'Ibanga',
    'pharmacy.trust_desc': 'Iyo utumije imiti igengwa n\'amategeko, CareMart ihuza komande yawe na farumasi yemewe kugira ngo yitegurwe neza. Ibyo watumije byose bikugeraho bipfunyitse mu ibanga rikomeye.',
    'pharmacy.slider_title': 'Amafarumasi Yemewe Dufatanyije mu Rwanda',
    'pharmacy.slider_subtitle': 'Abafatanyabikorwa mu buvuzi batanze serivisi z\'imiti no kuboneza urubyaro',
    'pharmacy.certified_active': 'Iremewe & Irakora',
    'pharmacy.moh_certified': 'Yemewe na Minisiteri y\'Ubuzima',

    // Header and Dropdowns
    'header.user_greeting': 'Umunyamuryango w\'Ingenzi',
    'header.track_order_code': 'Kurikirana Kode ya Komande',
    'header.account_orders': 'Konti Yanjye & Ibyo Natumije',
    'header.download_app': 'Kumanura Porogaramu ya Telefoni',
    'header.sign_out': 'Gusohoka',
    'header.signin_or_track': 'Injira cyangwa ukurikirane kode y\'ibyo watumije',
    'header.order_tracking_portal': 'Aho Gukurikiranira Komande',
    'header.login': 'Kwinjira',
    'header.create_account': 'Kurema Konti ku Buntu',
    'header.download_app_full': 'Kumanura Porogaramu ya Mudasobwa/Telefoni',
    'header.menu': 'Ibikubiyemo',
    'header.app_button': 'App',

    // Cart Drawer
    'cart.discrete_cart': 'Icyibo Cyawe Cy\'Ibanga',
    'cart.unique_items': 'ibicuruzwa bitandukanye',
    'cart.empty_title': 'Icyibo cyawe kiracyarimo ubusa',
    'cart.empty_desc': 'Sura ibicuruzwa byacu by\'isuku n\'ubuzima bwite byizewe.',
    'cart.start_shopping': 'Tangira Kugura',
    'cart.each': 'kuri kimwe',
    'cart.promo_placeholder': 'Kode y\'igabanyirizwa (urug: DISCRETION10)',
    'cart.coupon_label': 'Kuponi',
    'cart.off': 'yagabanyijwe',
    'cart.apply': 'Koresha',
    'cart.remove': 'Gukuraho',
    'cart.subtotal_label': 'Igiteranyo cy\'ibanze',
    'cart.discount_label': 'Igabanyirizwa',
    'cart.total_label': 'Igiteranyo cyose',
    'cart.discretion_billing_box': 'Bikugeraho bipfunyitse mu gasanduku kadasize ikirango. Kwishyura byandikwaho "SS Global".',
    'cart.proceed_checkout': 'Komeza ku Kwishyura mu Mutekano',

    // Wishlist Page
    'wishlist.confidential_tag': 'Ibyo Wabitswe mu Ibanga',
    'wishlist.title': 'Ibyifuzo Byanjye Byihariye',
    'wishlist.saved_count': 'Byabitswe',
    'wishlist.empty_title': 'Nta cyo urabika mu byifuzo',
    'wishlist.empty_desc': 'Bika ibicuruzwa hano kugira ngo uzongere kubibona mu ibanga cyangwa uzabigure byihuse.',
    'wishlist.explore_catalog': 'Reba Ibyo Dufite Byose',

    // Product Card & Badges
    'badge.offer': 'KUGABANYIRIZWA',
    'badge.best_seller': 'IKYAKUNZWE CYANE',
    'badge.secure_toys': 'IBANGA N\'ISUKU',

    // Product Detail Page
    'product.save_amount': 'Uzigamye',
    'product.quantity': 'Ingano :',
    'product.in_stock': 'Birasigaye mu bubiko',
    'product.available': 'bihari',
    'product.add_to_cart': 'Shyira mu Ikarita',
    'product.buy_now_1click': 'Gura Ubu Ako Kanya',
    'product.add_to_wishlist': 'Bika mu Byifuzo',
    'product.in_wishlist': 'Biri mu Byifuzo Byite',
    'product.suggested_title': 'Ibicuruzwa Byakugirirwa Inama',
    'product.more_items_in': 'Ibindi bicuruzwa muri',
    'product.view_all_products': 'Reba Ibicuruzwa Byose',

    // Checkout Page
    'checkout.title': 'Kwishyura mu Mutekano',
    'checkout.shipping_address_title': '1. Aho Bikoherezwa mu Ibanga',
    'checkout.full_name': 'Amazina Yose *',
    'checkout.phone_number': 'Nimero ya Telefoni (Kuri SMS y\'Ubutumwa) *',
    'checkout.street_address': 'Aderesi y\'Umuhanda *',
    'checkout.apartment_landmark': 'Inzu / Ikimenyetso cy\'Ahantu',
    'checkout.city_district': 'Umujyi / Akarere *',
    'checkout.country': 'Igihugu',
    'checkout.delivery_instructions': 'Amabwiriza yo Kugezaho (Ibanga)',
    'checkout.delivery_instructions_ph': 'urug: Sigira ipaki ku biro mu gasanduku gasanzwe, umpamagare uhageze.',
    'checkout.payment_method_title': '2. Uburyo bwo Kwishyura (Gusuzuma Ako Kanya)',
    'checkout.momo_title': 'MTN Mobile Money (MoMo)',
    'checkout.momo_desc': 'Ubutumwa buhita buza kuri telefoni (078/079)',
    'checkout.airtel_title': 'Airtel Money (Rwanda)',
    'checkout.airtel_desc': 'Ubutumwa buhita buza kuri telefoni (072/073)',
    'checkout.momo_phone_section_momo': 'Nimero ya MTN Mobile Money',
    'checkout.momo_phone_section_airtel': 'Nimero ya Airtel Money',
    'checkout.enter_momo_number': 'Injiza nimero ya Mobile Money (urug: 0788123456 cyangwa 0731234567) *',
    'checkout.prompt_instruction': 'Nukanda kuri Ishyura & Tanga Komande, ubutumwa bwo kwishyura buhita buza kuri telefoni yawe kandi sisitemu ihita ibyemeza ako kanya.',
    'checkout.order_items': 'Ibyatumijwe',
    'checkout.qty': 'Ingano :',
    'checkout.items_subtotal': 'Igiteranyo cy\'ibicuruzwa',
    'checkout.grand_total': 'Igiteranyo Rusange',
    'checkout.discretion_assured': 'Ibanga n\'Umutekano 100%',
    'checkout.discretion_desc': 'Ibyo watumije bizapfunyikwa mu gasanduku gasanzwe katarimo izina cyangwa ikirango cy\'iduka.',
    'checkout.pay_and_place': 'Ishyura & Tanga Komande',
    'checkout.processing_payment': 'Kwishyura Birimo Gukorwa...',

    // Shop Page & Filters & Product Grid
    'shop.title': 'Ibicuruzwa Byose Byihariye',
    'shop.desc': 'Reba ibikoresho by\'ubuzima, isuku n\'umunezero byizewe.',
    'shop.filters_button': 'Akayunguruzo',
    'shop.active_filters': 'Ibyayunguruwe :',
    'shop.showing_items': 'ibicuruzwa byihariye',
    'shop.showing': 'Hagaragajwe',
    'shop.sort_by': 'Gutunganya ku :',
    'shop.sort_featured': 'Ibyatoranyijwe & Byiza',
    'shop.sort_price_asc': 'Igiciro : Guhera ku gito',
    'shop.sort_price_desc': 'Igiciro : Guhera ku kinini',
    'shop.sort_rating': 'Ibyakiriwe neza cyane',
    'shop.sort_newest': 'Ibigezweho bishya',
    'shop.reset_all': 'Gusubiza byose uko byari biri',
    'shop.category_label': 'Icyiciro',
    'shop.all_products': 'Ibicuruzwa Byose',
    'shop.max_price': 'Igiciro ntarengwa :',
    'shop.brand_label': 'Ubwoko (Brand)',
    'shop.all_brands': 'Amoko Yose',
    'shop.min_rating': 'Amanota yo hejuru ya',
    'shop.and_above': 'no hejuru',
    'shop.in_stock_only': 'Ibihari Gusa',
    'shop.clear_all': 'Kuruhura byose',
    'shop.filter_options': 'Ibyo Guhitamo mu Kuyungurura',
    'shop.no_products_title': 'Nta bicuruzwa bihuye n\'ibyo mwashatse',
    'shop.no_products_desc': 'Gerageza guhindura igiciro ntarengwa, guhindura icyiciro, cyangwa gusiba ibyo mwashakishije.',

    // Footer
    'footer.discrete_store_desc': 'CareMart ni iduka rya mbere mu Rwanda ryo kugura iby\'ubuzima bw\'imyororokere n\'isuku mu ibanga rikomeye.',
    'footer.quick_links': 'Aho Wagera Byihuse',
    'footer.customer_service': 'Serivisi y\'Abakiriya',
    'footer.confidential_packaging': 'Kugezwaho Ibicuruzwa mu Ibanga',
    'footer.rights': 'Uburenganzira bwose burabitswe.',
    'footer.privacy_policy': 'Amabwiriza y\'Ibanga n\'Umutekano',
    'footer.terms': 'Amategeko n\'Amabwiriza',

    // Contact
    'contact.title': 'Ubufasha n\'Ibibazo mu Ibanga',
    'contact.subtitle': 'Abakozi bacu biteguye kugufasha amasaha 24/7 mu ibanga rikomeye.',
    'contact.call_us': 'Hamagara Ubufasha',
    'contact.whatsapp_us': 'Kuvugana kuri WhatsApp',
    'contact.location': 'Kigali, Rwanda',

    // FAQ Page
    'faq.tag': 'Ubufasha & Umucyo',
    'faq.title': 'Ibibazo Bikunze Kubazwa',
    'faq.subtitle': 'Ibyo ukeneye kumenya byose ku mutekano w\'ibanga, gupfunyika no kwizerwa kw\'ibicuruzwa byacu.',
    'faq.q1': 'Ikarito yanjye izaba imeze ite ningeraho ?',
    'faq.a1': 'Ibicuruzwa byose bipfunyikwa mu makarito asanzwe y\'ikigina cyangwa amabahasha arinda ibirimo. Nta kimenyetso cy\'iduka, izina ry\'igicuruzwa cyangwa ifoto bibaho ku gapfunyiko k\'inyuma cyangwa ku rupapuro rwanditseho.',
    'faq.q2': 'Ni irihe zina rizagaragara kuri konte yanjye / Mobile Money ?',
    'faq.a2': 'Kugira ngo habeho ibanga risesuye mu mafaranga, kwishyura byose byandikwa mu izina ryisanzuye rya "CM Retail" cyangwa "CM Online".',
    'faq.q3': 'Ese ibicuruzwa byanyu byujuje ubuziranenge bwo kurinda umubiri ?',
    'faq.a3': 'Yego. Buri gicuruzwa cyakozwe mu bikoresho byujuje ubuziranenge bwo kwa muganga kandi byapimwe neza byemejwe n\'inzobere.',
    'faq.q4': 'Bifata igihe kingana iki ngo mbone ibyo naguize ?',
    'faq.a4': 'Ibyo waguze mbere ya saa munani z\'amanywa (2:00 PM) bipfunyikwa bikoherezwa uwo munsi i Kigali (mu minota 30 kugeza kuri 90).',
    'faq.q5': 'Mwakira gusubiza ibicuruzwa bite ?',
    'faq.a5': 'Kubera amabwiriza yo kwirinda no kurinda isuku y\'abantu, ibyakinguwe ntibisubizwa. Ariko ikintu cyose kigifunze neza nk\'uko cyavuye mu ruganda cyasubizwa mu minsi 30.',
    'faq.q6': 'Nshobora gukurikirana aho ikarito igeze ntawe ubonye ibirimo ?',
    'faq.a6': 'Yego. Uhita ubona uburyo bwo gukurikirana kuri konte cyangwa terefone yawe, ukabona aho ubutumwa bugeze nta mazina y\'ibirimo agaragara.',

    // Contact Page
    'contact.support_title': 'Ubufasha Bw\'Abakiriya mu Ibanga',
    'contact.support_desc': 'Ufite ibibazo ku bipfunyitswe mu ibanga, amasaha yo kugezwaho ibyo waguze cyangwa ubuziranenge bw\'ibicuruzwa ? Abakozi bacu biteguye kugufasha 24/7.',
    'contact.channels_title': 'Uburyo bwo Kutuvugisha Ako Kanya',
    'contact.email_support': 'Ubufasha kuri Imeyili Yizewe',
    'contact.response_time': 'Igisubizo mu masaha 2',
    'contact.phone_whatsapp': 'Guhamagara & WhatsApp',
    'contact.whatsapp_chat': 'Kuvugana kuri WhatsApp',
    'contact.call_now': 'Hamagara Ako Kanya',
    'contact.availability_247': 'Kuwa Mbere - Ku Cyumweru: Amasaha 24/7',
    'contact.office_title': 'Ibiro Byihariye by\'Ibanga',
    'contact.office_location': 'Ikigo cy\'Ibicuruzwa mu Ibanga i Kigali',
    'contact.office_promise': 'Ikarito ifunze itanditsweho ibirimo',
    'contact.form_title': 'Ohereza Ubutumwa mu Ibanga',
    'contact.your_name': 'Amazina Yawe *',
    'contact.name_placeholder': 'urugero: Marie Mutoni',
    'contact.your_email': 'Imeyili Yawe *',
    'contact.email_placeholder': 'wowe@urubuga.com',
    'contact.your_phone': 'Nimero ya Terefone (Si ngombwa)',
    'contact.subject_label': 'Impamvu',
    'contact.sub_order_shipping': 'Ibyo Naguze & Kugezwaho mu Ibanga',
    'contact.sub_product_guidance': 'Inama ku Bikoresho n\'Ibicuruzwa',
    'contact.sub_pharmacy_inquiry': 'Ibibazo ku Bafatanyabikorwa ba Farumasi',
    'contact.sub_billing_privacy': 'Kwishyura & Ibanga',
    'contact.sub_return_request': 'Gusaba Guhindura cyangwa Gusubiza',
    'contact.your_message': 'Ubutumwa Bwawe *',
    'contact.placeholder_msg': 'Twagufasha iki ku byo waguze mu ibanga...',
    'contact.send_btn': 'Ohereza Ubutumwa mu Ibanga',

    // Terms Page
    'terms.title': 'Amategeko n\'Amabwiriza yo Kugura',
    'terms.effective_date': 'Yatangiye gukurikizwa: Nyakanga 2026',
    'terms.age_title': '1. IBIJANYE N\'IMYAKA',
    'terms.age_desc': 'Ugomba kuba ufite byibuze imyaka 18 (cyangwa imyaka y\'ubukure yemewe n\'amategeko) kugira ngo ugure ibicuruzwa kuri CareMart. Gutumiza ibicuruzwa bisobanura ko wujuje iyo myaka.',
    'terms.safety_title': '2. IMINYWERE N\'UMUTEKANO W\'IBICURUZWA',
    'terms.safety_desc': 'Ibicuruzwa byose byo kwita ku mubiri n\'ubuzima bw\'imyororokere kuri CareMart bigenewe abantu bakuru. Abakiriya bagirwa inama yo gusoma amabwiriza mbere yo gukoresha igicuruzwa icyo aricyo cyose.',
    'terms.pricing_title': '3. IBICIRO N\'IBIHARI',
    'terms.pricing_desc': 'Ibiciro biri ku rubuga biri mu mafaranga y\'u Rwanda (Frw). Twibikiye uburenganzira bwo guhindura ibiciro, amaporomosiyo n\'ingano y\'ibihari mbere yo kwemeza ubutumwa.',
    'terms.return_title': '4. ISUKU N\'AMABWIRIZA YO GUSUBIZA',
    'terms.return_desc': 'Kubera amabwiriza yo kurinda ubuzima n\'isuku, ibicuruzwa byakinguwe cyangwa byakoreshejwe ntibisubizwa. Ibikiri mu bipfunyiko byabyo by\'uruganda bishobora gusubizwa mu minsi 30.',

    // Privacy Policy Page
    'privacy.title': 'Amabwiriza y\'Ibanga n\'Umutekano',
    'privacy.last_updated': 'Ivugururwa rya nyuma: Nyakanga 2026',
    'privacy.guarantee_title': 'Isezerano Ryacu ryo Kutagurisha Amakuru Yawe',
    'privacy.guarantee_desc': 'Kuri CareMart, ibanga ryawe niyo ntego yacu ya mbere. Ntitugurisha, ntitukodesha, ntitunasangiza amakuru yawe y\'ubuzima, ibyo waguze cyangwa imeyili yawe n\'abandi bantu cyangwa ibigo byo kwamamaza.',
    'privacy.encryption_title': '1. GUKINGIRA NO KURINDA AMAKURU',
    'privacy.encryption_desc': 'Imikoranire yose hagati ya telefone/mudasobwa yawe n\'urubuga rwacu icungirwa umutekano ukomeye wa SSL 256-bit. Amakuru yawe arinzwe mu buryo bugezweho.',
    'privacy.shipping_title': '2. GPFUNYIKA MU IBANGA',
    'privacy.shipping_desc': 'Ibicuruzwa bipfunyikwa gusa mu makarito asanzwe y\'ikigina cyangwa amabahasha arinda ibirimo. Inyuma nta jambo na rimwe riranga ibirimo ryanditseho.',
    'privacy.statement_title': '3. IBANGA RYA RELEVE / MOMO',
    'privacy.statement_desc': 'Ubutumwa bwo kwishyura kuri Mobile Money cyangwa banki buzagaragaza gusa izina risanzwe rya "CM Retail" cyangwa "CM Online", nta kintu kizavuga ibyaguzwe.',
    'privacy.cookies_title': '4. AMABWIRIZA YA COOKIES',
    'privacy.cookies_desc': 'Dukoresha cookies z\'ingenzi gusa mu kubika ibyo washyize mu cyibo, ibyo ukunda no gukomeza kwinjira muri konte yawe.',

    // Order Tracking Page
    'tracking.official_badge': 'Ahabanza ho Gukurikirana Ibyo Waguze',
    'tracking.page_title': 'Kurikirana aho Icyo Waguze Kigeze',
    'tracking.page_desc': 'Shyiramo Nimero y\'Icyo Waguze (Order ID) na Nimero ya Terefone wakoresheje ugura urebe aho umumotari n\'ubutumwa bwawe bigeze.',
    'tracking.tab_id_phone': 'Kurikirana na Order ID & Terefone',
    'tracking.tab_phone_only': 'Wibagiwe Order ID ? Kurikirana na Terefone',
    'tracking.heading_id_phone': 'Shyiramo Order ID na Terefone',
    'tracking.heading_phone_only': 'Shaka Order ID ukoresheje Terefone yawe',
    'tracking.label_order_id': 'Nimero y\'Ibyo Waguze (Order ID) *',
    'tracking.label_phone': 'Nimero ya Terefone Wakoresheje *',
    'tracking.phone_help': 'Shyiramo nimero ya MoMo, Airtel cyangwa terefone watanze wishyura urebe Order ID yawe.',
    'tracking.btn_find_and_track': 'Shaka Order ID & Kurikirana',
    'tracking.btn_track_now': 'Kurikirana Ako Kanya',
    'tracking.found_multiple': 'Twabonye ibyo waguze inshuro {count} kuri iyi terefone :',
    'tracking.recent_account_orders': 'Guhitamo byihuse muri konte yawe :',
    'tracking.paid_success': 'Yishyuwe neza',
    'tracking.placed_on': 'Yatumiwe kuwa :',
    'tracking.copy_btn': 'Koporora',
    'tracking.copied_btn': 'Byakoporowe',
    'tracking.timeline_title': 'Aho Umumotari na Parcel Bigeze Ako Kanya',
    'tracking.step_paid': 'Ibyo Waguze Byemejwe',
    'tracking.step_paid_sub': 'Kwishyura kwemejwe',
    'tracking.step_sealed': 'Ikarito yafunzwe mu ibanga',
    'tracking.step_sealed_sub': 'Ikarito itanditseho ibirimo',
    'tracking.step_driver': 'Umumotari w\'Icyerekezo',
    'tracking.step_driver_sub': 'Umumotari ari mu nzira',
    'tracking.step_delivered': 'Byagejejweho nyirabyo',
    'tracking.step_delivered_sub': 'Kugezwaho uwo munsi',
    'tracking.courier_update_title': 'Amakuru Mashya y\'Ibyo Waguze n\'Umumotari',
    'tracking.courier_note_prefix': 'Icyo waguze kiri mu cyiciro cya',
    'tracking.courier_note_suffix': 'Umumotari azahamagara kuri iyi terefone nageraho aho wamusabye kukigeza.',
    'tracking.parcel_contents': 'Ibirimo mu Ikarito',
    'tracking.items_count': 'ibicuruzwa',
    'tracking.qty': 'Ingano :',
    'tracking.grand_total_paid': 'Amafaranga Yose Yishyuwe',
    'tracking.customer_shipping_info': 'Amakuru y\'Umukiriya & Aho Byoherezwa',
    'tracking.customer_name': 'Amazina y\'Umukiriya',
    'tracking.destination': 'Aho Byoherezwa',
    'tracking.instructions': 'Amabwiriza y\'Uburyo bwo Kubitanga',
    'tracking.confidential_promise': 'Kugezwaho mu Ibanga 100%',
    'tracking.confidential_box_desc': 'Ikarito ifunze itanditsweho igezwa vuba.',
    'tracking.not_found_title': 'Nta Butumwa Buhuye n\'Ibi Biranga',
    'tracking.not_found_desc': 'Ntitwashoboye kubona ibicuruzwa bihuye na Order ID na terefone mwashyizemo. Gerageza kureba neza cyangwa wandikire ubufasha.',

    // Categories Page
    'catpage.badge': 'Ibyiciro Byose by\'Ibicuruzwa',
    'catpage.title': 'Shakisha Ukurikije Icyiciro cy\'Ubuzima',
    'catpage.subtitle': 'Kuva ku dukingirizo twemewe n\'abaganga kugeza ku bikoresho by\'isuku n\'urukundo by\'agaciro. Bipfunyitse 100% mu ibanga.',
    'catpage.products_count': 'Ibicuruzwa',
    'catpage.browse_cat': 'Gura'
  }
};

export const LANGUAGE_OPTIONS: { code: Language; name: string; nativeName: string; flag: string }[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'rw', name: 'Kinyarwanda', nativeName: 'Kinyarwanda', flag: '🇷🇼' },
];

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('caremart_language') as Language;
      if (saved && (saved === 'en' || saved === 'fr' || saved === 'rw')) {
        return saved;
      }
      // Check browser navigator language
      const navLang = navigator.language?.toLowerCase() || '';
      if (navLang.startsWith('fr')) return 'fr';
      if (navLang.startsWith('rw')) return 'rw';
    }
    return 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('caremart_language', lang);
      document.documentElement.lang = lang;
    }
  };

  useEffect(() => {
    if (typeof document !== 'undefined') {
      document.documentElement.lang = language;
    }
  }, [language]);

  const t = (key: string, defaultText?: string): string => {
    const langDict = translations[language] || translations.en;
    if (langDict[key]) {
      return langDict[key];
    }
    const enDict = translations.en;
    if (enDict[key]) {
      return enDict[key];
    }
    return defaultText || key;
  };

  const translateCategory = (categoryName?: string): string => {
    if (!categoryName) return '';
    const trimmed = categoryName.trim();
    const langCategories = CATEGORY_TRANSLATIONS[language] || CATEGORY_TRANSLATIONS.en;
    if (langCategories[trimmed]) {
      return langCategories[trimmed];
    }
    // Case-insensitive fallback
    const keyMatch = Object.keys(langCategories).find(
      (k) => k.toLowerCase() === trimmed.toLowerCase()
    );
    if (keyMatch && langCategories[keyMatch]) {
      return langCategories[keyMatch];
    }
    return categoryName;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, translateCategory }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
